version: '3'
services:
  app:
    image: golang:1.20.6-alpine3.18
    container_name: gin-dockerized
    restart: always
    command: sh -c "go mod tidy && go build -o bin/server server/movie/main.go"
    ports:
      - 3003:3003
    working_dir: /app
    volumes:
      - ./:/app
  postgres:
    image: postgres:latest
    container_name: practice_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/postgres:/data/db
