version: '3'
services:
  app:
    container_name: gin-dockerized
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=movie
      - DATABASE_HOST=postgresdb
    tty: true
    build: .
    ports:
      - 3003:3003
    restart: on-failure
    volumes: 
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - test_network


  postgresdb:
    image: postgres:latest
    container_name: practice_postgres
    ports:
      - 5432:5432
    networks:
      - test_network
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=movie
      - DATABASE_HOST=postgresdb

volumes:
  pg_data:

networks:
  test_network:
    driver: bridge