CREATE TABLE "movies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY  NOT NULL,
  "title" varchar NOT NULL,
  "genre" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()) NOT NULL
);