// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
)

type Movie struct {
	ID        int32          `json:"id"`
	Title     sql.NullString `json:"title"`
	Genre     sql.NullString `json:"genre"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
